apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-devops-project  
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AyaAdel11/Cloud-DevOps-Project.git
    targetRevision: HEAD
    path: .  
  destination:
    server: https://kubernetes.default.svc
    namespace: ivolve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
